# NHN SecureManager
secure-key-manager:
  url: https://api-keymanager.cloud.toast.com
  app-key: mcXcTmrnbRezlila
  local-key: gaship

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: 142ea0b649994beb8650736c271f5e13
  username: eggplant
  password: e55472d5d7ea4bbdb6f3149e1ed597e5

redis:
  host: a93c53427dd84868bdc3402d94270bf4
  port: 6379
  password: c61df19084544df5a11f5c9a57abb6c2
  database: 24

